### PR TITLE
 Fix for error for valid domain that does not resolve

### LINKED ISSUE #184: DNS Check throws exception for some valid domains
We are seeing exception reports for ARSoft.Tools.Net.Dns.DnsSecRecursiveDnsResolver whilst resolving pretty basic domain like 'cloudapp.net' suggesting there is a fault in that library.

### PR DESCRIPTION
**Pull request by Marcus-L**
* Added test for "cloudapp.net" to the Unit Tests (not caught by existing tests because it was a _valid domain_, but did not resolve to an IP address)
* Fixes #184

### CODE REVIEW

**Comment by webprofusion-chrisc** [comment]
Thanks!

**Comment by webprofusion-chrisc** [comment]
Prepping this for a new release later today. Thanks again.

**Comment by Marcus-L** [comment]
No worries! Sorry I let that one slip through.

**Comment by Marcus-L** [comment]
Hopefully that means some people are actually trying out the TLS-SNI challenge!

**Pull request merged**
