### PR TITLE
Better handling for large number of sites

### PR DESCRIPTION
**Pull request by Marcus-L**
Optimized ItemManager for large numbers of sites, changed test back to 100K sites. I think test is actually more stressful than the UI due to the way it loads the sites one by one rather than in bulk. I was able to load the test settings file from #177 in the UI pretty quickly and navigate around without any UI delay with this optimization.

### CODE REVIEW

**Comment by Marcus-L** [comment]
Added conversion of settings to Sqlite. Single site update/delete can happen in < 40ms even with 100K managed sites. There's a one-time upgrade when converting from json settings, so the first load will be slow since it loads Json and saves Sqlite settings.

**Comment by webprofusion-chrisc** [comment]
Thanks @Marcus-L ! I've been playing with something similar in the settingsdb and vaultdb branches but this aligns well with that. Storing the json is the simplest idea and lets us stay flexible on schema, the only other thing I'd like to consider is storing the 'header' info (Name, Expiry Date, Item Type etc) so that we could present and filter the Managed Sites list UI without parsing the JSON. I've started working on the overall approach to splitting the app into UI and a Service (#179) which is currently a windows service hosting a .net web api bound to localhost. In this configuration the managed site list will have an upper limit on the number of results displayed by default.

**Comment by Marcus-L** [comment]
I saw your settingsdb branch and tried out the LiteDB code first since it seemed like it had a nicer programming model, but it ended up being pretty slow to load 100K records in my tests, not sure why. I would have thought the binary serialization might have been faster. Should be pretty easy to swap out if you wanted to give it another go. The SQLite stuff I did was pretty boilerplate, so I'm not attached to it at all. I didn't try "Exclusive" mode or "InsertBulk" (since I wanted to use "Upsert" and there was no "UpsertBulk").

**Comment by Marcus-L** [comment]
The header idea is pretty good, that'd help with startup time a bit. Might be tricky to handle the site search filter if we wanted to keep the notes & domain names as part of that filter, and would require a refactor on the ItemManager to focus on single insert/updates to load/save individual settings by id and also update to the UI to load site settings on demand. Worth it? I wouldn't mind giving it a try later if you think so, but probably am not going to have a ton of free time for the next few weeks.

**Comment by webprofusion-chrisc** [comment]
Yeah thanks very much for this, I think I'll merge this now as is. The 'localservice' branch is the one I've just started working on and it has major structural changes, so best to wait for the dust to settle before doing too much more.

**Pull request merged**
