### PR TITLE
Add more localizable resources

### PR DESCRIPTION
**Pull request by iccfish**
- Certify.Core language resources added, almost strings in progresspanel can now be localized
- Added zh-Hans translation to new resources.

### CODE REVIEW

**Comment by iccfish** [comment]
Seems that there's some conflicts. I'll resolve then later, please do not merge now 😄

**Comment by webprofusion-chrisc** [comment]
Thanks! When I updated the .resx the other day (the 'Cancel' english version was in Chinese) it also automatically rewrites the SR.Designer.cs comments in english so it makes it look like there are more changes than there are.

**Comment by iccfish** [comment]
All resources in SR.Designer.cs  was in English, so it doesn't matter use which version, I just take HEAD from origin to resolve the conflication 😄 

The problem was certify.core was changed after I last pull so this need to be merged manually.

**Comment by iccfish** [comment]
Conflicts has been merged.

**Pull request merged**
