### PR TITLE
Add Powershell Hooks for Pre/Post Request Actions

### PR DESCRIPTION
**Pull request by Marcus-L**
I realized that RRAS's SSTP VPN (whew, that's a lot of acronyms) could use the SSL certificate installed in IIS by Certify to do VPN encryption, but it wouldn't automatically switch to the auto-renewed certificates until the service was restarted (at least in Windows Server 2008 R2). I figured that was a good use case for a request hook as talked about in webprofusion/certify#63. I added post- and pre-request hooks as well as the ability to modify the RequestConfig such as updating `ManagedItem.RequestConfig.WebsiteRootPath` as discussed in webprofusion/certify#146.

Also exposed the website root directory in the UI in case there is a special directory (like ASP.NET Core's convention for storing static files in wwwroot) that the challenge files should be based out of:

screenshot_090917_112604_pm

Example script: `restart rras.ps1`
```powershell
param($result)
if ($result.IsSuccess) {
	write-output "Restarting RRAS"
	Net Stop RemoteAccess
	Net Start RemoteAccess
	write-output "Done"
}
```

I also tested out auto-updating the WebsiteRootDirectory: `test.ps1`
```powershell
param($result)
$id = $result.ManagedItem.GroupId
[xml]$xml = . "$env:windir\system32\inetsrv\appcmd" list config /section:system.applicationHost/sites
$path = $xml.SelectSingleNode("//site[@id=$id]/application[@path='/']/virtualDirectory/@physicalPath").Value
$result.ManagedItem.RequestConfig.WebsiteRootPath = $path
write-output "Path Updated: $path"
```

This is probably the sort of change that would be good to update the documentation or wiki alongside with making, since it's non-obvious how the hooks work if you didn't already know what they did. Is there any way for me to do that? Thanks!

### CODE REVIEW

**Comment by webprofusion-chrisc** [comment]
Wow, this is brilliant! I'll merge this now. We should probably normally chat about these types of changes before you make them as there are some design considerations to work through, like in this case generic scripted hooks (cmd, powershell or node) would have been favourable, and a method for passing common arguments (pfx path etc) is required. Typically people want this functionality so they can then transform and apply the certificate (like in mail servers etc).

**Comment by webprofusion-chrisc** [comment]
Btw, you have restored my faith in the decision to make this project Open Source.

**Comment by webprofusion-chrisc** [comment]
Although you did add a goto. I haven't used goto for about 25 years, not sure how I feel about that :)

**Comment by Marcus-L** [comment]
Hi Chris, I'm glad the PR was appreciated. I'll try to discuss more beforehand for PRs on the individual issues they are addressing, I definitely did think about your concerns about cmd or node or the plugin path though. I figured that 1) people doing server admin on Windows are probably doing it in PowerShell already and 2) PowerShell is the best integrated with .NET for passing objects back and forth to scripts, and 3) you could just call out to cmd or node or whatever from the PowerShell script.

Btw, you can access the PFX path (or anything else from the Config) from the PowerShell script by using the $result object - in this case $result.ManagedItem.CertificatePath (which should be updated to the new path in the Post-Request hook). Oh, that reminds me -- where would be a good place to contribute to documentation or wiki? This probably needs docs somewhere.

Finally, yup, I felt pretty guilty dropping that goto in there, but that method already was maxing out indentation at 11 levels deep and I'd have felt more guilty of adding one more level to skip the entire certificate request code. 😢 I briefly considered adressing the [refactor FIXME](https://github.com/webprofusion/certify/blob/master/src/Certify.Core/Management/CertifyManager.cs#L208) to clean things up but I was too afraid of breaking things.

**Comment by webprofusion-chrisc** [comment]
Hi Marcus,
Regarding docs, if you get a chance could you start a docs folder in the project root and add a markdown doc. Plan would we to be able to re-use these docs as units within the certifytheweb.com site, possibly use them within the app or at least link to them (which is why it's not just a wiki).

**Comment by Marcus-L** [comment]
Committed some docs in 7f1b28f.  Thanks for the commit access, I'll only commit docs directly for now, everything else I'll still run through PRs so you can review first.

**Comment by webprofusion-chrisc** [comment]
Outstanding stuff. Very much appreciated.

**Comment by JesterEE** [comment]
I was working with this feature on a x64 Windows Server 2012 R2 install, and was trying to use the IIS Snap-in within Powershell and kept getting errors that the class was not registered when testing my script.  I think I am running into [this issue posted on SO](https://stackoverflow.com/questions/3501001/windows-powershell-snap-in-for-iis-fails-on-32-bit).  I made the test script in the answers to test how Certify is running Powershell and found it was running the 32-bit version of Powershell on my 64-bit system.

test_powershell_bitness.ps1
```powershell
[IntPtr]::Size
```
Returns ```4``` instead of ```8```

Can this feature please be updated to run the Powershell executable of the correct bitness?

**Comment by webprofusion-chrisc** [comment]
Hi @JesterEE thanks for your feedback. This is covered in the docs at https://docs.certifytheweb.com/docs/script-hooks.html but thanks for your bitness check that could be useful. The next version of the app (v4) will be 64bit only and therefore will have a 64bit powershell process.

**Comment by JesterEE** [comment]
@webprofusion-chrisc Thanks for the link to the documentation on this.  I am still having an issue with it running 32-bit powershell using the script hook template.

Here is my pre-request script to disable a URL rewrite rule to tackle an issue I had way back in the day #2.

```powershell
param($result)
Set-Alias ps64 "$env:windir\system32\WindowsPowerShell\v1.0\powershell.exe" 
ps64 -args $result -command {
  $result = $args[0]
  Write-Output $result.IsSuccess
  If (-NOT ([Security.Principal.WindowsPrincipal] [Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole(`
      [Security.Principal.WindowsBuiltInRole] "Administrator")){
      Write-Warning "You do not have Administrator rights to run this script!`nPlease re-run this script as an Administrator!"
  }
  If ([IntPtr]::Size -eq 4){
      Write-Warning "Running in 32-bit mode!`nPlease re-run this script in 64-bit mode!"
  }
  Import-Module WebAdministration
  Set-WebconfigurationProperty '/system.webserver/rewrite/globalRules/rule[@name="MyProxyRule"]' -Name Enabled -Value False
}
```

Note: On my system, the 64-bit Powershell is in `system32` as I don't have a `sysnative` directory as the documentation states.

Modifying IIS requires administrator permissions and using `WebAdministration` required 64-bit Powershell.  Testing the script will show that my 32-bit test is being triggered, the warning is being shown, and the script failing.

I'm not sure why 64-bit Powershell isn't being launched properly?  Any thoughts?

**Comment by JesterEE** [comment]
@webprofusion-chrisc Thanks for the pointer!  FYI, I tackled webprofusion/certify#2 with this:
 ```powershell
# Certify Pre-Request Hook
# Disable URL rewrite rules and create a temporary HTTP site for certificate validation
param($result)
Set-Alias ps64 "$env:windir\sysnative\WindowsPowerShell\v1.0\powershell.exe"
ps64 -args $result -command {
  $result = $args[0]
  Write-Output $result.IsSuccess
  Import-Module WebAdministration
  Set-WebconfigurationProperty '/system.webserver/rewrite/globalRules/rule[@name="HttpToHttps"]' -Name Enabled -Value False
  Set-WebconfigurationProperty '/system.webserver/rewrite/globalRules/rule[@name="ReverseProxy"]' -Name Enabled -Value False
  New-WebSite -Name "CertifyTempSite" -Port 80 -HostHeader "www.mywebserver.com" -PhysicalPath "C:\Local\Path\To\Use"
}
```

```powershell
# Certify Post-Request Hook
# Enable URL rewrite rules and remove the temporary HTTP site for certificate validation
param($result)
Set-Alias ps64 "$env:windir\sysnative\WindowsPowerShell\v1.0\powershell.exe"
ps64 -args $result -command {
  $result = $args[0]
  Write-Output $result.IsSuccess
  Import-Module WebAdministration
  Set-WebconfigurationProperty '/system.webserver/rewrite/globalRules/rule[@name="HttpToHttps"]' -Name Enabled -Value True
  Set-WebconfigurationProperty '/system.webserver/rewrite/globalRules/rule[@name="ReverseProxy"]' -Name Enabled -Value True
  Remove-WebSite -Name "CertifyTempSite"
}
```

**Comment by webprofusion-chrisc** [comment]
@JesterEE interesting! The next version of the app will have an optional http challenge server process (in front of IIS in the http pipeline) to avoid having to configure IIS.

**Pull request merged**
