### PR TITLE
Support tls-sni-01 challenges

### PR DESCRIPTION
**Pull request by Marcus-L**
Implement feature issue #158. Was going to wait for the tls-sni-01 PR to get merged into ACMESharp but it hasn't been looked at yet so I switched the ACMESharp submodule to my tls-sni branch temporarily so this change can get merged in to prevent drifting too far from master. I touched a lot of files and have already had to resolve conflicts while merging in updates. 

You'll have to update your submodule after pulling to compile for testing:
```shell
git submodule sync
git submodule update --init --recursive --remote
```

Side q's: should the dependency be changed from a submodule to nuget after the PR gets merged in now that [packages are available](https://github.com/ebekker/ACMESharp/wiki/%5BWIP%5D-Downloads:-NuGet-Packages)? Or was there another reason for doing a submodule?

Please let me know if you have any questions or modification requests.

### CODE REVIEW

**Comment by webprofusion-chrisc** [comment]
Thanks, this is awesome. I'll need to have a good look through it and do a bit of my own research - I haven't previously looked into tls-sni-01 much.

Re: ACMESharp submodule, we did briefly use the nuget packages but then reverted to using the submodule because the NuGet package didn't have the BouncyCastle support, looks like this is resolved. On the other hand you can't then do things like temporary forks (as in this case) if you use the nuget packages.

**Comment by webprofusion-chrisc** [comment]
Ok, merged now. You had code to modify the hosts file somewhere, is that still a thing or do we not need that?

Further to this (notes for myself as much as anything):

We need to not reference ACMESharp directly in ManagedItemSettings, so we will need to use an intermediate enum for supported challenge types in RequestConfig.ChallengeType, likewise ChallengeTypes in AppModel.cs

Feels like the Test config option shouldn't have code to set the primary domain/group id etc, but not sure where this concern should sit.

**Comment by webprofusion-chrisc** [comment]
Also further to this, tns-sni-02 could be implemented as a variation? 
https://shredzone.org/maven/acme4j/challenge/tls-sni-02.html

**Comment by Marcus-L** [comment]
Awesome, thanks for the merge! I'll start up another PR to address your concerns about the reference to ACMESharp in ManagedItemSettings (and the PrimaryDomain/GroupId stuff). The only reason for the ACMESharpCompat reference is for the challenge const strings (ex: "tls-sni-01" and "http-01"), so that could be moved anywhere. Do you have a suggestion for which namespace to move it to?

RE: hosts file, yup the hosts file modification is still in there: https://github.com/webprofusion/certify/blob/191bfe6e715ec84b1b0820ded0bf3ce811bc6189/src/Certify.Core/Management/VaultManager.cs#L1073 The Certify UI already runs as administrator so we should be OK when using the UI (unless there exists a configuration where the hosts file is not in `[system folder i.e. C:\winddows\system32]\drivers\etc\hosts`). The scheduled task isn't guaranteed to run as admin though, so people could run into problems there. The hosts file modification is actually only required for local testing, so maybe if it fails while attempting a scheduled renewal we could somehow ignore that failure. I'll look into that if it ends up being an issue. Hopefully a bunch of people will try it out and report any issues, I tested on IIS 10 (windows 10 pro) and IIS 7.5 (win2008serverR2) and it worked but we'll see if it works for other configs. Maybe the local-testing should be removed from the live cert request entirely, and only run on-demand from the UI. If the test succeeds locally, there should be no need to run it before doing live cert requests. Famous last words, right?

RE: setting the defaults for domain & groupID in the UI for testing, I had the same concern but also wasn't sure where to do the setting. On the one hand it seems as though PrimaryDomain should be a calculated value on the ManagedSite model, since it is the result of the DomainOptions configuration. But on the other hand, it is nice to have it statically set and easily viewed in the config json file. WRT GroupId, it could probably be set in `Website_SelectionChanged`:
 https://github.com/webprofusion/certify/blob/191bfe6e715ec84b1b0820ded0bf3ce811bc6189/src/Certify.UI/Controls/ManagedItemSettings.xaml.cs#L162
I'll look into it in more detail either tomorrow or the day after.

RE: tls-sni-02, I looked into it while implementing -01 and the spec is actually very similar to the -01 code, there would not be very many changes to implement it (I don't think, anyway). I could definitely take a stab at it but it doesn't seem like there's much of a point to do it until there's a public endpoint to test against. (If you set up an ACME Pebble instance for testing I'd give it a go though 😃). Or we could just wait for the official v2 test endpoint. I think it'll be AnyDayNow™️...  I'm not sure there'd be much point in supporting both challenges once tls-sni-02 is supported with the test & live endpoints, once ACME v2 is up we should just migrate everyone to the latest version of the challenges for maximum future-proofing. There will supposedly be ample time where both versions of the challenge will be supported, so we would not be in any danger of being incompatible.

**Comment by webprofusion-chrisc** [comment]
Re: hosts, I think we should expect that to fail in a number of cases (AV products, group policy settings, read only attribute etc) - often it's guarded to prevent spoofing important sites.

This SO question has an approach for overriding host header that could maybe be relevant?
https://stackoverflow.com/questions/9161575/building-an-httpping-that-can-overide-a-host-file

Don't worry about the refactoring/ACMESharp refs just now if it's not clear where they would go. I can have a look and see.

**Comment by webprofusion-chrisc** [comment]
Have had another look at this re: config checks/manual test and have created a new issue to track. Basically we should test more of the domains (all SAN entries) and we should do it first before anything else.:
https://github.com/webprofusion/certify/issues/165

**Comment by cpu** [comment]
@Marcus-L RE: Testing a TLS-SNI-02 challenge. In addition to the Pebble implementation we actually have [TLS-SNI-02 challenge support in Boulder](https://github.com/letsencrypt/boulder/blob/9d324631a71959084c35746d9d2a551f9995857a/va/va.go#L551:L589), but we don't have the feature flag to enable it deployed to staging/prod. We made the choice to hold that for the V2 API but if you were interested in trying it sonner you can run Boulder locally changing the [`BOULDER_CONFIG` docker-compose.yml parameter](https://github.com/letsencrypt/boulder/blob/b80b129d1a459005ebf52862136108cdc1528be3/docker-compose.yml#L10) to `test/config-next`. That will use a config that enables the `AllowTLS02Challenges` feature flag for the [RA](https://github.com/letsencrypt/boulder/blob/b0c7bc1bee009f83bae9ff327052e316cdd19706/test/config-next/ra.json#L46) and the [CA](https://github.com/letsencrypt/boulder/blob/9d324631a71959084c35746d9d2a551f9995857a/test/config-next/ca.json#L134) respectively and you should start to get back authorizations that have DNS-01, HTTP-01, TLS-SNI-01, and TLS-SNI-02 challenges available.

**Pull request merged**
