### PR TITLE
Improving Code Protection from NullReferenceException

### PR DESCRIPTION
**Pull request by GermanAizek**
Commit: Additional nullable checks and dispose objects before return, fixed possible bug with locker string

### CODE REVIEW

**Comment by webprofusion-chrisc** [comment]
Hi @GermanAizek thanks for your contribution, can you confirm which refactoring tool you used for this (visual studio, rider or resharper?). 

There's quite a lot to review here - while I agree with the general idea, handling nulls instead of letting the app hit (and ideally log) an exception does change the potential effects of some things. 

For example if a plugin provider is null then something important went wrong and we may want the exception to happen.

**Comment by webprofusion-chrisc** [comment]
Having reviewed this further I think I'm happy to merge it then retest a few areas, can you sign this CLA? You just need to sign in with github and agree, it's a standard boilerplate : https://cla-assistant.io/webprofusion/certify

**Comment by GermanAizek** [comment]
@webprofusion-chrisc, hi I signed c.l.a. license.
(visual studio, rider or resharper) none of the following.

use to search for similar flaws:
[SonarQube](https://www.sonarqube.org/)
[Pex](http://research.microsoft.com/Pex/)
[Spec#](http://research.microsoft.com/SpecSharp/)
[CodeIt.Right](http://submain.com/codeit.right)
[PRQA QA·C#](http://www.programmingresearch.com/products/qacsharp/)
[Coverity Prevent™ for C#](http://www.coverity.com/html/coverity-prevent-for-c%23.html)

**Comment by webprofusion-chrisc** [comment]
Thanks very much!

**Comment by webprofusion-chrisc** [comment]
Free license keys are available for open source contributors if you want one, you just create an account at https://certifytheweb.com/register/createaccount then email support {at} certifytheweb.com and I'll setup the license.

**Pull request merged**
