### PR TITLE
Updates to AccessControl Tests

### PR DESCRIPTION
**Pull request by jrnelson90**
Existing test was split out into multiple tests, and basic new happy path tests were added for two untested methods in AccessControl.

### CODE REVIEW

**Comment by webprofusion-chrisc** [comment]
Ouch :) I'm working on access control in a different branch (access_control, based on certify_server) and it's a WIP and very different to the original model. I appreciate the changes but they will be too different to what we now have. Let's shelve this one and use it for inspiration later.

I'm not sure how best to avoid stepping on each others toes with changes. I'm used to free reign and have prior work in progress on the certify-server branch. Let me see what I can merge back into development today.

**Comment by jrnelson90** [comment]
Perhaps some kind of kanban board could help keep us from duplicating efforts? That's what I've used at my last two positions for task management.

In fact I believe that GitKraken has some type of Kanban board capabilities built into it, and GitHub may have something similar as well.

**Comment by webprofusion-chrisc** [comment]
Yeah I'm thinking something similar, in this particular case there is just too much stuff sitting in certify-server so I need to work through merging that for you to have any chance of working on the right codebase!

**Comment by webprofusion-chrisc** [comment]
Ok, all certify-server branches have been merged into development now (it's a lot!), so you can start fixes from development with less chance of conflicting changes.

**Pull request closed without merging**
