### PR TITLE
UI Fixes and new features plus refactoring

### PR DESCRIPTION
**Pull request by Marcus-L**
* Misc UI updates
  * Keyboard shortcuts (CTRL-F, DEL) on site list
  * Better "discard changes?" detection and handling
  * Fix colors on Server 2008 R2 (or computers with Aero turned off)
  * Made the DesignViewModel usable for testing (uncomment the "new DesignViewModel()" line in AppModel.cs)
  * Fix bug where site list filter stopped working after any settings save
* Core update
  * Centralize change detection on BindableBase objects, automatically bubble up and down IsChanged

I apologize for the size of the PR, but most of the changes (aside from the color fixes) are linked together pretty tightly. I did try to group the changes together into logical commits so they'd be digestable in smaller chunks. 

I'd be a little more careful than usual merging this in without testing, honestly the keyboard navigation stuff was super difficult to get the bugs out of, so although I spent (many!) hours testing it, I wouldn't be surprised if there were a few more in there.

Feel free to pop any questions about this into the dev slack, we can chat async if our timezones aren't overlapping.

### CODE REVIEW

**Comment by webprofusion-chrisc** [comment]
Wow, that's quite a set of changes. I'll cut a release with what we have currently then let this bake for a bit. I'm not sure I understand the reasons for all of the changes but I'll have a look through. Pretty brave tackling the change detection stuff!

**Comment by Marcus-L** [comment]
Yeah... I've learned that Xaml change detection can be pretty inscrutable. I tried to make the change tracking logic centralized in BindableBase, it was scattered in both core and ui, so hopefully will be easier to maintain and debug in the future. Please let me know if you have any questions about the changes. Many were just attempts to reduce the LOC count or simplify the data model to make things easier to understand for someone new wanting to contribute. Definitely still more to work on but every bit counts.

**Comment by Marcus-L** [comment]
Added a commit (https://github.com/webprofusion/certify/pull/203/commits/3021635ec01c3b6b5d9d9b313edd3969b75e9cfa) to help with UI freezes when navigating between sites with 100's of DomainOptions. Should fix #197, I'm not sure about #177 since I don't have a "real" config to test renewing multiple sites with 100's of SANs.

**Comment by webprofusion-chrisc** [comment]
Thanks, merging that now so we won't get further merge conflicts. I'm currently looking at a different problem related to load/save of settings. When I fired up the new (released) version on my server I had less managed sites than I should have but don't understand why, so doing some tests now.

**Pull request merged**
