### PR TITLE
Development

### PR DESCRIPTION
**Pull request by boscorelly**
french

### CODE REVIEW

**Comment by webprofusion-chrisc** [comment]
@boscorelly thanks for submitting this! Sorry, I cannot accept this PR as it is because it is against master but is based on development, so there are a huge number of unrelated commits. It would have to be submitted against 'development'.

There is a lot of UI work happening just now in preparation for v4.0 I'd recommend holding off a couple of weeks before submitting further translations, key elements of the UI are still changing.

**Comment by boscorelly** [comment]
Hi,

yes i have seen this, and i was wanting it to be in devel branch.

I will try to push it to devel instead =)

**Comment by boscorelly** [comment]
How can i pull requests to devel ?... I can only pull to master...

**Comment by webprofusion-chrisc** [comment]
Sorry I haven't tried it myself but I think there are some instructions here: https://help.github.com/articles/changing-the-base-branch-of-a-pull-request/

**Comment by boscorelly** [comment]
github
It seems i have no rights to do that...

**Pull request closed without merging**
