### PR TITLE
Adding SimpleDNSPlus API functionality

### PR DESCRIPTION
**Pull request by alphaz18**
Adding the ability to do verification for Simple DNS Plus Server Users.
3 fields for the provider, server IP, authkey and authsecret, where authkey is the http api username and authsecret is the password. Must use Basic Auth in Simple DNS Plus HTTP API configuration.

### CODE REVIEW

**Comment by webprofusion-chrisc** [comment]
Thanks! This is much appreciated. Will review at the weekend. Just a thought: We need to see if we can consolidate the methods used to trim domains to the target zone in a common way between providers e.g. _acme-challenge.subdomain for subdomain.example.com etc. We have different methods happening currently. I also need to add UI so users can just pick zone from a dropdown (and fix the broken credentials UI in the current dev branch).

**Comment by benmcnix** [comment]
I apologize for my GitHub ignorance, but does this mean we can expect wildcard automation to become available for us SimpleDNS users?

**Comment by alphaz18** [comment]
I'm all for that trimming domains, however, depending on the provider, they require different formats. for example, some providers only allow root zones as zones, ie example.com and do not allow sub.example.com, they see sub as sub records, others require the subdomain to be a zone, and yet others require the record name to be the complete fqdn, as opposed to others who just want the record name ie. _acme-challenge, so thats why there are different things going on for different providers I believe. i suppose if we want to rid the dns providers of all those extra parsing code, we'd have to send it a DnsRecord with variables that cover all possible scenarios: 
personally, i would probably just have the RecordName as is right now, as the full fqdn of the record, ie. _acme-challenge.subdomain.example.com, then have different methods to parse return correct parameter ie. method DNSRecord.ParseRootDomain DNSRecord.ParseSubDomain DNSRecord.ParseLastRecordName DNSRecord.ParseNoRootRecordName ? i think that would handle all the possible scenarios, so if you had _acme-challenge.sub1.sub2.example.com, 
ParseRootDomain: example.com
ParseSubDomain: sub1.sub2.example.com
ParseLastRecordName: _acme-challenge
ParseNoRootRecordName: _acme-challenge.sub1.sub2
what do you think? that way the dns providers can just call on different methods of the dnsrecord object instead of having to distinguish and parse their own stuff

**Comment by webprofusion-chrisc** [comment]
Yes, that sounds good. There is a base class that some of the providers are using so methods could go there. I'm stabilising v4 so things like refactoring are probably something for a future release anyway.

**Pull request merged**
